{
 "title": "Hedging",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Overall Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(error_type) (rate(resilience_polly_pipeline_duration_milliseconds_count{pipeline_name=\"Hedging-standard-hedging\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Overall Attempts Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(attempt_number, error_type, exception_type) (rate(resilience_polly_strategy_attempt_duration_milliseconds_count{pipeline_name=\"Hedging-standard-hedging\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Attempts Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Overall Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(event_name) (rate(resilience_polly_strategy_events{pipeline_name=\"Hedging-standard-hedging\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "sum by(event_name) (rate(resilience_polly_strategy_events{pipeline_name=\"Hedging-standard-hedging-endpoint\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}